---
trigger:
  - master
variables:
  terraformVersion: 0.12.18
  agentPool: 'ubuntu-18.04'
  action: plan

stages:
  - stage: Sandbox_Plan
    displayName: "Sandbox plan"
    jobs:
      - job: Validate
        pool:
          vmImage: ${{ variables.agentPool }}
        steps:
          - template: pipeline-templates/terraform-plan.yaml
            parameters:
              zone: 'sandbox'
              build: $(Build.BuildNumber)
              agentPool: ${{ variables.agentPool }}
              terraformVersion: ${{ variables.terraformVersion }}

  - stage: Sandbox_Apply
    dependsOn: Sandbox_Plan
    displayName: "Sandbox Apply"
    condition: and(succeeded(), eq(variables['action'], 'apply'))
    jobs:
      - template: pipeline-templates/terraform-apply.yaml
        parameters:
          zone: 'sandbox'
          build: $(Build.BuildNumber)
          agentPool: ${{ variables.agentPool }}
          terraformVersion: ${{ variables.terraformVersion }}



